spring:
  application:
    name: swiftboot-demo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
    open-in-view: false
logging:
  file: /var/log/swiftboot-demo.log
  level:
    root: INFO
    org.swiftboot: DEBUG
swiftboot:
  web:
    filter:
      # 跨域允许的范围
      corsAllowOrigin: 'localhost'
      # 允许的头
      allowHeaders:
        - sso_token
        - my_header
    model:
      autoGenerateId: true
      initData: true
      initBaseDir: /Users/allen/Workspace/github/swiftboot/swiftboot-web/src/test/resources/init/
      initBasePackages:
        - org.swiftboot.demo.model.entity
    validation:
      resultInJson: false
  service:
    redis:
      host: localhost
      port: 6379
  auth:
    enabled: true
    session:
      type: redis
      expireTime: 1800
      tokenKey: swiftboot_token
