spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swiftboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
      import_files: import.sql
logging:
  level:
    root: INFO
    org.swiftboot: DEBUG
    org.apache.shiro: DEBUG
swiftboot:
  shiro:
    cookie:
      domain: localhost
      path: /
      name: swiftboot_shiro_token
      maxAge: 300
    session:
      timeout: 300
      forceDisableRedirect: false
      redisGroup: shiro-session
  demo:
    init:
      users:
        -
          loginName: admin
          loginPwd: 12345678
        -
          loginName: yoda
          loginPwd: 12345678
        -
          loginName: luke
          loginPwd: 12345678
      roles:
        -
          name: admin
          desc: Administrator
        -
          name: manager
          desc: Manager
        -
          name: staff
          desc: Staff
      permissions:
        -
          code: 'goods'
          desc: '商品'
          permissions:
            -
              code: 'goods:create'
              desc: '创建商品'
            -
              code: 'goods:delete'
              desc: '删除商品'
        -
          code: 'order'
          desc: '订单'
          permissions:
            -
              code: 'order:list'
              desc: '订单列表'
            -
              code: 'order:query'
              desc: '订单查询'
            -
              code: 'order:create'
              desc: '创建订单'
            -
              code: 'order:delete'
              desc: '删除订单'
            -
              code: 'order:save'
              desc: '更新订单'
      rolePermRels:
        admin:
          - '*'
        manager:
          - 'goods:*'
          - 'order:list'
          - 'order:query'
          - 'order:delete'
        staff:
          - 'order:create'
          - 'order:query'
          - 'order:save'
      roleUserRels:
        admin:
          - 'admin'
        manager:
          - 'yoda'
        staff:
          - 'luke'