
spring:
  application:
    name: swiftboot-demo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
logging:
  level:
    root: INFO
    org.swiftboot: DEBUG
common:
  web:
    validation:
      result:
        json: true

swiftboot:
  web:
    model:
      autoGenerateId: false
    validation:
      resultInJson: false